#!/bin/bash

set -e

# Define the .env file path
ENV_FILE_PATH=".env"

# Clear the contents of the .env file
> "$ENV_FILE_PATH"

echo "AZURE_OPENAI_CHAT_DEPLOYMENT=$(azd env get-value AZURE_OPENAI_CHAT_DEPLOYMENT)" >> "$ENV_FILE_PATH"
echo "AZURE_OPENAI_CHAT_MODEL=$(azd env get-value AZURE_OPENAI_CHAT_MODEL)" >> "$ENV_FILE_PATH"
echo "AZURE_OPENAI_ENDPOINT=$(azd env get-value AZURE_OPENAI_ENDPOINT)" >> "$ENV_FILE_PATH"
echo "AZURE_TENANT_ID=$(azd env get-value AZURE_TENANT_ID)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_ACCOUNT=$(azd env get-value AZURE_COSMOSDB_ACCOUNT)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_DATABASE=$(azd env get-value AZURE_COSMOSDB_DATABASE)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_CONTAINER=$(azd env get-value AZURE_COSMOSDB_CONTAINER)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_USER_CONTAINER=$(azd env get-value AZURE_COSMOSDB_USER_CONTAINER)" >> "$ENV_FILE_PATH"
echo "AZURE_COSMOSDB_OAUTH_CONTAINER=$(azd env get-value AZURE_COSMOSDB_OAUTH_CONTAINER)" >> "$ENV_FILE_PATH"
echo "APPLICATIONINSIGHTS_CONNECTION_STRING=$(azd env get-value APPLICATIONINSIGHTS_CONNECTION_STRING)" >> "$ENV_FILE_PATH"
# Auth feature flags
echo "USE_FASTMCP_AUTH=$(azd env get-value USE_FASTMCP_AUTH)" >> "$ENV_FILE_PATH"
echo "USE_KEYCLOAK=$(azd env get-value USE_KEYCLOAK)" >> "$ENV_FILE_PATH"
KEYCLOAK_REALM_URL=$(azd env get-value KEYCLOAK_REALM_URL 2>/dev/null || echo "")
if [ -n "$KEYCLOAK_REALM_URL" ] && [ "$KEYCLOAK_REALM_URL" != "" ]; then
  echo "KEYCLOAK_REALM_URL=${KEYCLOAK_REALM_URL}" >> "$ENV_FILE_PATH"
fi
FASTMCP_AUTH_AZURE_CLIENT_ID=$(azd env get-value FASTMCP_AUTH_AZURE_CLIENT_ID 2>/dev/null || echo "")
if [ -n "$FASTMCP_AUTH_AZURE_CLIENT_ID" ] && [ "$FASTMCP_AUTH_AZURE_CLIENT_ID" != "" ]; then
  echo "FASTMCP_AUTH_AZURE_CLIENT_ID=${FASTMCP_AUTH_AZURE_CLIENT_ID}" >> "$ENV_FILE_PATH"
  echo "FASTMCP_AUTH_AZURE_CLIENT_SECRET=$(azd env get-value FASTMCP_AUTH_AZURE_CLIENT_SECRET)" >> "$ENV_FILE_PATH"
fi
echo "MCP_ENTRY=$(azd env get-value MCP_ENTRY)" >> "$ENV_FILE_PATH"
echo "MCP_SERVER_URL=$(azd env get-value MCP_SERVER_URL)" >> "$ENV_FILE_PATH"
echo "API_HOST=azure" >> "$ENV_FILE_PATH"
